"""Initial schema

Revision ID: fb3058cd2c69
Revises: 
Create Date: 2026-09-12 11:54:19.343114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb3058cd2c69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('holder_name', sa.String(length=255), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_tier', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risktierenum'), nullable=False),
    sa.Column('kyc_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_risk_tier'), 'accounts', ['risk_tier'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'PENDING_REVIEW', 'CLOSED', name='casestatusenum'), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('sla_due', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disposition', sa.Enum('FRAUD', 'NOT_FRAUD', 'SAR_FILED', name='dispositionenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reputation', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_table('entity_edges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('src_type', sa.String(length=32), nullable=False),
    sa.Column('src_id', sa.UUID(), nullable=False),
    sa.Column('dst_type', sa.String(length=32), nullable=False),
    sa.Column('dst_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.String(length=32), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entity_edge_dst', 'entity_edges', ['dst_type', 'dst_id'], unique=False)
    op.create_index('idx_entity_edge_src', 'entity_edges', ['src_type', 'src_id'], unique=False)
    op.create_table('ips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reputation', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mcc', sa.String(length=10), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reputation', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('GRAPH', 'TIMELINE', 'TYPOLOGY', 'MEDIA', 'NOTE', name='evidencekindenum'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Enum('AGENT', 'HUMAN', 'ANALYST', name='authorkindenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sar_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('narrative_md', sa.String(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'EDITED', 'APPROVED', 'REJECTED', name='sarstatusenum'), nullable=False),
    sa.Column('author', sa.Enum('AGENT', 'HUMAN', 'ANALYST', name='authorkindenum'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'version', name='uq_case_sar_version')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('counterparty_id', sa.UUID(), nullable=True),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('ip_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('channel', sa.Enum('CARD', 'TRANSFER', 'WALLET', name='channelenum'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['ip_id'], ['ips.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_ts'), 'transactions', ['ts'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('calibrated_prob', sa.Float(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVE', 'REVIEW', 'DECLINE', name='decisionenum'), nullable=False),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_hits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_decisions_decision'), 'decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_decisions_ts'), 'decisions', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_ts'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_decision'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_transactions_ts'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('sar_drafts')
    op.drop_table('evidence_items')
    op.drop_table('merchants')
    op.drop_table('ips')
    op.drop_index('idx_entity_edge_src', table_name='entity_edges')
    op.drop_index('idx_entity_edge_dst', table_name='entity_edges')
    op.drop_table('entity_edges')
    op.drop_table('devices')
    op.drop_table('cases')
    op.drop_index(op.f('ix_accounts_risk_tier'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
